#!/usr/bin/env python3
"""Add or refresh an app's screens on the site.

usage: python3 scripts/make-shots.py <app_id> <source_dir> <scene,scene,scene> [--landscape]

<source_dir>/<locale>/<scene>.png are raw app screens (portrait 1206×2622 from an iPhone 17
simulator, captured with XCUITest so there is no Dynamic Island; landscape 2622×1206). Locale folders
may use App Store codes (en-US, pt-BR, zh-Hans …); they are mapped to the site's 13 codes. A locale is
used only when all scenes exist. Writes public/shots/<app>/<locale>/<scene>.jpg (macOS sips) and
regenerates src/data/shots.ts from what is in public/shots. Also set `shots.scenes` in src/data/apps.ts.
"""
import json, os, subprocess, sys

SITE_LOCALES = ['en', 'ru', 'zh', 'es', 'fr', 'de', 'ja', 'ko', 'pt', 'ar', 'it', 'hi', 'he']
ALIAS = {'en-US': 'en', 'ar-SA': 'ar', 'de-DE': 'de', 'es-ES': 'es', 'fr-FR': 'fr', 'pt-BR': 'pt', 'zh-Hans': 'zh'}
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    if len(args) != 3:
        sys.exit(__doc__)
    app, src, scenes = args[0], args[1], args[2].split(',')
    landscape = '--landscape' in sys.argv
    done = []
    for src_loc in sorted(os.listdir(src)):
        loc = ALIAS.get(src_loc, src_loc)
        files = [os.path.join(src, src_loc, f'{s}.png') for s in scenes]
        if loc not in SITE_LOCALES or not all(os.path.exists(f) for f in files):
            continue
        out_dir = os.path.join(ROOT, 'public', 'shots', app, loc)
        os.makedirs(out_dir, exist_ok=True)
        for scene, f in zip(scenes, files):
            subprocess.run(['sips', '-s', 'format', 'jpeg', '-s', 'formatOptions', '80', '-Z', '1200' if landscape else '1304',
                            f, '--out', os.path.join(out_dir, f'{scene}.jpg')], check=True, capture_output=True)
        done.append(loc)
    print(app, 'locales:', ' '.join(sorted(done, key=SITE_LOCALES.index)) or 'none')

    # manifest from everything in public/shots
    manifest = {}
    shots_root = os.path.join(ROOT, 'public', 'shots')
    for a in sorted(os.listdir(shots_root)):
        if os.path.isdir(os.path.join(shots_root, a)):
            locs = [l for l in os.listdir(os.path.join(shots_root, a)) if l in SITE_LOCALES]
            manifest[a] = sorted(locs, key=SITE_LOCALES.index)
    ts = '// Generated by scripts/make-shots.py: the locales each app has screens for (others fall back to English).\n'
    ts += 'export const shotLocales: Record<string, string[]> = ' + json.dumps(manifest, indent=2).replace('"', "'") + '\n'
    open(os.path.join(ROOT, 'src', 'data', 'shots.ts'), 'w').write(ts)


if __name__ == '__main__':
    main()
